<aside id="filters">
   <div class="bordered stacked mb-3 p-0">
      <h3 class="title m-0">Văn phòng theo Quận</h3>
      <div class="list-group">
         <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-1">Quận 1</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-2">Quận 2</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-3">Quận 3</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-4">Quận 4</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-5">Quận 5</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-6">Quận 6</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-7">Quận 7</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-8">Quận 8</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-9">Quận 9</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-10">Quận 10</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-11">Quận 11</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-12">Quận 12</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-binh-thanh">Quận Bình Thạnh</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-phu-nhuan">Quận Phú Nhuận</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-tan-binh">Quận Tân Bình</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-tan-phu">Quận Tân Phú</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-go-vap">Quận Gò Vấp</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-thu-duc">Quận Thủ Đức</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/quan-binh-tan">Quận Bình Tân</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huyen-cu-chi">Huyện Củ Chi</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huyen-can-gio">Huyện Cần Giờ</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huyen-hoc-mon">Huyện Hóc Môn</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huyen-nha-be">Huyện Nhà Bè</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huyen-binh-chanh">Huyện Bình Chánh</a>            
      </div>
   </div>
   <div class="bordered stacked mb-3 p-0">
      <h3 class="title m-0">Văn phòng theo Đường</h3>
      <div class="list-group">
         <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-nguyen-kiem">Đường Nguyễn Kiệm</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-phan-van-tri-2">Đường Phan Văn Trị</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-le-van-tho">Đường Lê Văn Thọ</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-phan-van-tri">Đường Phan Văn Trị</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-tran-thi-nghi">Đường Trần Thị Nghỉ</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-phan-huy-ich">Đường Phan Huy Ích</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-nguyen-tuan">Đường Nguyễn Tuân</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-le-loi-2">Đường Lê Lợi</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/duong-nguyen-binh-khiem">Đường Nguyễn Bỉnh Khiêm</a>            
      </div>
   </div>
   <div class="bordered stacked mb-3 p-0">
      <h3 class="title m-0">Văn phòng theo Hướng</h3>
      <div class="list-group">
         <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/chua-xac-dinh">Chưa xác định</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-tay-nam">Hướng Tây Nam</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-tay-bac">Hướng Tây Bắc</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-dong-nam">Hướng Đông Nam</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-dong-bac">Hướng Đông Bắc</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-dong">Hướng Đông</a>                  <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-tay">Hướng Tây</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-nam">Hướng Nam</a>                    <a class="list-group-item list-group-item-action" href="/van-phong-cho-thue/huong-bac">Hướng Bắc</a>            
      </div>
   </div>
</aside>